spring.application.name=Course-Shop

server.port=3979

spring.datasource.url=jdbc:mysql://localhost:3306/course_shop
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true    
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = Thymeleaf Configuration
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

#cloudinary config
cloudinary.cloud.name=dhtjbtn1o
cloudinary.api.key=794143318917716
cloudinary.api.secret=RFsKQN3sGxmnXaoxcxgBPfH6wAI

#jwt config
jwt.secret=codeMasterSecret123456789012345678901234567890123456789012345678901234567890
jwt.expiration=86400000

#Admin config
admin.username=admin
admin.password=Admin@123
admin.email=admin20@gmail.com

#mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codemaster3979@gmail.com
spring.mail.password=eldqewkxseketyps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#VN payments config
vnpay.tmn-code=MP02DNA0
vnpay.hash-secret=SG58R2CC38M90JD42K9PDX5SMV19D7IH
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:3979/payments/vnpay-return
vnpay.ipn-url=http://localhost:3979/api/payments/ipn