spring.application.name=Course-Shop

server.port=3979

debug=false

logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.org.springframework.web.multipart=DEBUG
logging.level.com.jungle.courseshop.controller=DEBUG

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.resolve-lazily=false

# ===============================
# = DATASOURCE (MySQL Railway)
# ===============================
#spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:57246/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=VAOaXbIHIqlpSOnNbNdKUiuCiFVIrdbw
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/course_shop
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = Thymeleaf Configuration
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# ===============================
# = Cloudinary Configuration
# ===============================
cloudinary.cloud.name=dhtjbtn1o
cloudinary.api.key=794143318917716
cloudinary.api.secret=RFsKQN3sGxmnXaoxcxgBPfH6wAI

# ===============================
# = JWT Configuration
# ===============================
jwt.secret=codeMasterSecret123456789012345678901234567890123456789012345678901234567890
jwt.expiration=86400000

# ===============================
# = Admin Configuration
# ===============================
admin.username=admin
admin.password=Admin@123
admin.email=admin20@gmail.com

# ===============================
# = Mail Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codemaster3979@gmail.com
spring.mail.password=eldqewkxseketyps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# = VNPay Configuration
# ===============================
vnpay.tmn-code=MP02DNA0
vnpay.hash-secret=SG58R2CC38M90JD42K9PDX5SMV19D7IH
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:3979/payments/vnpay-return
vnpay.ipn-url=http://localhost:3979/api/payments/ipn


spring.ai.openai.api-key=csk-e9e8e3fxwy4mmywd4jj8rwtpyd39xyxhf6ewfy553j9te6wr
spring.ai.openai.base-url=https://api.cerebras.ai/v1


VNPT_EKYC_API_URL=https://api.idg.vnpt.vn
VNPT_EKYC_TOKEN_ID=499dea31-d6df-3a3b-e063-62199f0a94be
VNPT_EKYC_TOKEN_KEY=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKGTp3d9pQkFwCXR3tG3u3QgDDJFG3l7AbYJZvhnqBbuNORh7yKcnzPJcqabyCCBpuFP6DLVJE15TwL4BZ8Qv0MCAwEAAQ==
VNPT_EKYC_ACCESS_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmFuc2FjdGlvbl9pZCI6IjRmMDdjMjI2LTNkNjEtNDhjOC1iYzBiLTUzZmVlNTJmMDMzNiIsInN1YiI6IjM5MjY4MDc1LWZkZjMtMTFmMC05ZGUwLTU1NzY5Yjc3NDY1YiIsImF1ZCI6WyJyZXN0c2VydmljZSJdLCJ1c2VyX25hbWUiOiJuZ3V5ZW50aGFuaGRhdDE2MTAyMDA0MzEyQGdtYWlsLmNvbSIsInNjb3BlIjpbInJlYWQiXSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QiLCJuYW1lIjoibmd1eWVudGhhbmhkYXQxNjEwMjAwNDMxMkBnbWFpbC5jb20iLCJleHAiOjE3Njk4NzQ1NTMsInV1aWRfYWNjb3VudCI6IjM5MjY4MDc1LWZkZjMtMTFmMC05ZGUwLTU1NzY5Yjc3NDY1YiIsImF1dGhvcml0aWVzIjpbIlVTRVIiXSwianRpIjoiNmUzNWUwNDEtZTc0ZS00ZjNlLWJmZDItNGMwNGJkZTRkNzhhIiwiY2xpZW50X2lkIjoiY2xpZW50YXBwIn0.H_KTYR6q1BRVmJaJEV338ZgwMLnYZsOJLoQFHOLqaznpmZPTzGyujz5kNKgvAfeFg0LPdQ6Eu6EQX7WHUEILMlEU7Usr6LuDzYUmF8PDSF1W-WYQHdTe4b2gDWmGDvaPoWdq27yxHR4aQ8aUHFpXwNNTcrCrsJ9RcYg701_mnlz40x8TEIXQhQUf64FxjosOsP44lreHJ8mpqF7qNSyHkIs2HcwGluxflnN6gmmYjIC8MC-lGl2aNTuyKNrEhH9rKlRmEDXkE3Z7KHMygYY1bJ18AepCHkFLoY2UFuVDoSYeUoyHcCrsKbiaWirlJnQlIwVjWCQbzb0o1I_s7HO5OQ